---
title: "Lax"
author: "Matt Johnson"
date: "8/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

Lets try to build a field


```{r}
Draw.Half.Lax = function() {
ggplot() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.ticks.y=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  geom_segment(mapping = aes(x=0, y=5, xend=5, yend=5)) +
  geom_segment(mapping = aes(x=0, y=0, xend=5, yend=0)) +
  geom_segment(mapping = aes(x=0, y=0, xend=0, yend=5)) +
  geom_segment(mapping = aes(x=5, y=0, xend=5, yend=5)) +
  geom_segment(mapping = aes(x=0, xend=5, y=1, yend=1)) +
  geom_segment(mapping = aes(x=.75, xend=.75, y=1, yend=5)) +
  geom_segment(mapping = aes(x=4.25, xend=4.25, y=1, yend=5)) +
  geom_point(mapping = aes(x=2.5, y=4), size = 20, alpha = .5, color = "black") +
  geom_segment(mapping = aes(x=2.4, xend=2.6, y=4, yend=4)) +
  geom_segment(mapping = aes(x=1, xend=4, y=4, yend=4), lty=2) +
  geom_segment(mapping = aes(x=1, xend=1, y=1, yend=4), lty=2) +
  geom_segment(mapping = aes(x=1, xend=4, y=2, yend=2), lty=2) +
  geom_segment(mapping = aes(x=4, xend=4, y=1, yend=4), lty=2) +
  geom_segment(mapping = aes(x=1, xend=4, y=3, yend=3), lty=2) +
  geom_segment(mapping = aes(x=2, xend=2, y=1, yend=4), lty=2) +
  geom_segment(mapping = aes(x=3, xend=3, y=1, yend=4), lty=2) +
  geom_label(mapping = aes(x=1.5, y=3.5), label = "A", size = 10) +
  geom_label(mapping = aes(x=1.5, y=2.5), label = "D", size = 10) +
  geom_label(mapping = aes(x=1.5, y=1.5), label = "G", size = 10) +
  geom_label(mapping = aes(x=2.5, y=3.5), label = "B", size = 10) +
  geom_label(mapping = aes(x=3.5, y=3.5), label = "C", size = 10) +
  geom_label(mapping = aes(x=3.5, y=2.5), label = "F", size = 10) +
  geom_label(mapping = aes(x=3.5, y=1.5), label = "I", size = 10) +
  geom_label(mapping = aes(x=2.5, y=2.5), label = "E", size = 10) +
  geom_label(mapping = aes(x=2.5, y=1.5), label = "H", size = 10)
}

Draw.Full.Lax = function(Ride.Clear) {
  ggplot() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.ticks.y=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title = element_blank()) +
    geom_segment(mapping = aes(x=0, xend=5, y=10, yend=10)) +
    geom_segment(mapping = aes(x=0, xend=5, y=0, yend=0)) +
    geom_segment(mapping = aes(x=0, xend=0, y=0, yend=10)) +
    geom_segment(mapping = aes(x=5, xend=5, y=0, yend=10)) +
    geom_segment(mapping = aes(x=2.5, xend=2.5, y=0, yend=10)) +
    geom_segment(mapping = aes(x=3.75, xend=3.75, y=0, yend=10)) +
    geom_segment(mapping = aes(x= 1.25, xend=1.25, y=0, yend=10)) +
    geom_segment(mapping = aes(x=0, xend=1.25, y=2, yend=2)) +
    geom_segment(mapping = aes(x=0, xend=1.25, y=8, yend=8)) +
    geom_segment(mapping = aes(x=3.75, xend=5, y=2, yend=2)) +
    geom_segment(mapping = aes(x=3.75, xend=5, y=8, yend=8)) +
    geom_point(mapping = aes(x=.3, y=5), size = 10, alpha = .5) +
    geom_point(mapping = aes(x=4.7, y=5), size = 10, alpha = .5) +
    geom_segment(mapping = aes(x=.3, xend=.3, y=4.8, yend=5.2)) +
    geom_segment(mapping = aes(x=4.7, xend=4.7, y=4.8, yend=5.2)) +
    geom_segment(mapping = aes(x=2, xend=3, y=2, yend=2)) +
    geom_segment(mapping = aes(x=2, xend=3, y=8, yend=8)) +
    geom_point(mapping = aes(x=Ride.Clear$x, y=Ride.Clear$y, shape = Ride.Clear$Type), show.legend = T, size = 8) +
    scale_shape_manual(values=c(1,5))
}

Goal.Frame = function () {
  ggplot() +
    theme(axis.title.x=element_blank(),
          axis.text.x=element_blank(),
          axis.ticks.x=element_blank(),
          axis.ticks.y=element_blank(),
          axis.title.y=element_blank(),
          axis.text.y=element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          legend.title = element_blank()) +
    geom_segment(mapping = aes(x=-1, y=1, xend=1, yend=1), size=5) + #top
    geom_segment(mapping = aes(x=-1, y=1.403, xend=-1, yend=-20), size=6) + #left
    geom_segment(mapping = aes(x=1, y=1.403, xend=1, yend=-20), size=6) + #right
    geom_segment(mapping = aes(x=-1, xend=1, y=-13.5, yend=-13.5), lty=2) +
    geom_segment(mapping = aes(x=-1, xend=1, y=-6.5, yend=-6.5), lty=2) + 
    geom_segment(mapping = aes(x=-.333, xend=-.333, y=1.4, yend=-20), lty=2) +
    geom_segment(mapping = aes(x=.333, xend=.333, y=1.4, yend=-20), lty=2) +
    geom_label(mapping = aes(x=-.666, y=-2.5), label="A") +
    geom_label(mapping = aes(x=0, y=-2.5), label="B") +
    geom_label(mapping = aes(x=.666, y=-2.5), label="C") +
    geom_label(mapping = aes(x=-.666, y=-10), label="D") +
    geom_label(mapping = aes(x=0, y=-10), label="E") +
    geom_label(mapping = aes(x=.666, y=-10), label="F") +
    geom_label(mapping = aes(x=-.666, y=-17.5), label="G") +
    geom_label(mapping = aes(x=0, y=-17.5), label="H") +
    geom_label(mapping = aes(x=.666, y=-17.5), label="I") +
    xlim(-2, 2)
}

Draw.FO = function () {
  ggplot() +
    theme(axis.title.x=element_blank(),
          axis.text.x=element_blank(),
          axis.ticks.x=element_blank(),
          axis.ticks.y=element_blank(),
          axis.title.y=element_blank(),
          axis.text.y=element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          legend.title = element_blank()) +
    geom_segment(mapping = aes(x=0, xend=5, y=10, yend=10)) +
    geom_segment(mapping = aes(x=0, xend=5, y=0, yend=0)) +
    geom_segment(mapping = aes(x=0, xend=0, y=0, yend=10)) +
    geom_segment(mapping = aes(x=5, xend=5, y=0, yend=10)) +
    geom_segment(mapping = aes(x=2.5, xend=2.5, y=0, yend=10)) +
    geom_segment(mapping = aes(x=3.75, xend=3.75, y=0, yend=10)) +
    geom_segment(mapping = aes(x= 1.25, xend=1.25, y=0, yend=10)) +
    geom_segment(mapping = aes(x=0, xend=1.25, y=2, yend=2)) +
    geom_segment(mapping = aes(x=0, xend=1.25, y=8, yend=8)) +
    geom_segment(mapping = aes(x=3.75, xend=5, y=2, yend=2)) +
    geom_segment(mapping = aes(x=3.75, xend=5, y=8, yend=8)) +
    geom_segment(mapping = aes(x=2, xend=3, y=2, yend=2)) +
    geom_segment(mapping = aes(x=2, xend=3, y=8, yend=8)) +
    geom_point(mapping = aes(x=.3, y=5), size = 10, alpha = .5) +
    geom_point(mapping = aes(x=4.7, y=5), size = 10, alpha = .5) +
    geom_segment(mapping = aes(x=.3, xend=.3, y=4.8, yend=5.2)) +
    geom_segment(mapping = aes(x=4.7, xend=4.7, y=4.8, yend=5.2)) +
    geom_point(mapping = aes(x=2.5, y=5), shape = 4, size = 5) +
    geom_segment(mapping = aes(x=2, xend=2, y=2.5, yend=7.5), lty=2) +
    geom_segment(mapping = aes(x=3, xend=3, y=2.5, yend=7.5), lty=2) +
    geom_segment(mapping = aes(x=2, xend=3, y=2.5, yend=2.5), lty=2) +
    geom_segment(mapping = aes(x=2, xend=3, y=7.5, yend=7.5), lty=2) +
    geom_segment(mapping = aes(x=2, xend=3, y=6.25, yend=6.25), lty=2) +
    geom_segment(mapping = aes(x=2, xend=3, y=3.75, yend=3.75), lty=2) +
    geom_segment(mapping = aes(x=2, xend=3, y=5, yend=5), lty=2) +
    geom_label(mapping = aes(x=2.25, y=6.9), label="A") +
    geom_label(mapping = aes(x=2.75, y=6.9), label="B") +
    geom_label(mapping = aes(x=2.25, y=5.6), label="C") +
    geom_label(mapping = aes(x=2.75, y=5.6), label="D") +
    geom_label(mapping = aes(x=2.25, y=4.4), label="E") +
    geom_label(mapping = aes(x=2.75, y=4.4), label="F") +
    geom_label(mapping = aes(x=2.25, y=3.1), label="G") +
    geom_label(mapping = aes(x=2.75, y=3.1), label="H") +
    scale_shape_manual(values=c(1,5))
}
```

```{r}
Draw.Half.Lax()

Ride.Clear = data.frame(x=(c(.25, 1.25, .25, rep(2.5, 3), rep(3.75, 3), .6, rep(1.6, 2), rep(2.85, 3), rep(4.05, 3))), y=(c(rep(c(2, 5, 8), 3), 2.2, 3.4, 7.06, 3, 5, 7, 3, 5, 7)), Type=(c(rep("Clear", 9), rep("Ride", 9))))
Draw.Full.Lax(Ride.Clear)

Shots.Placement = data.frame(x=rnorm(20, mean=0, sd=.5), y=rnorm(20, mean=0, sd=.5))
Goal.Frame()

Draw.FO()
```




