---
title: "Lax"
author: "Matt Johnson"
date: "8/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

Lets try to build a field

```{r}
Draw.Half.Lax = function(Shots) {
ggplot() +
  # theme(axis.title.x=element_blank(),
  #       axis.text.x=element_blank(),
  #       axis.ticks.x=element_blank(),
  #       axis.ticks.y=element_blank(),
  #       axis.title.y=element_blank(),
  #       axis.text.y=element_blank(), 
  #       panel.grid.major = element_blank(),
  #       panel.grid.minor = element_blank()) +
  geom_segment(mapping = aes(x=0, y=5, xend=5, yend=5)) +
  geom_segment(mapping = aes(x=0, y=0, xend=5, yend=0)) +
  geom_segment(mapping = aes(x=0, y=0, xend=0, yend=5)) +
  geom_segment(mapping = aes(x=5, y=0, xend=5, yend=5)) +
  geom_segment(mapping = aes(x=0, xend=5, y=1, yend=1)) +
  geom_segment(mapping = aes(x=.75, xend=.75, y=1, yend=5)) +
  geom_segment(mapping = aes(x=4.25, xend=4.25, y=1, yend=5)) +
  geom_point(mapping = aes(x=2.5, y=4), size = 20, alpha = .5, color = "black") +
  geom_segment(mapping = aes(x=2.4, xend=2.6, y=4, yend=4)) +
  geom_count(mapping = aes(x=Shots$x, y=Shots$y), shape = 13, show.legend = F)
}

Draw.Full.Lax = function(Ride.Clear) {
  ggplot() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.ticks.y=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title = element_blank()) +
    geom_segment(mapping = aes(x=0, xend=5, y=10, yend=10)) +
    geom_segment(mapping = aes(x=0, xend=5, y=0, yend=0)) +
    geom_segment(mapping = aes(x=0, xend=0, y=0, yend=10)) +
    geom_segment(mapping = aes(x=5, xend=5, y=0, yend=10)) +
    geom_segment(mapping = aes(x=2.5, xend=2.5, y=0, yend=10)) +
    geom_segment(mapping = aes(x=3.75, xend=3.75, y=0, yend=10)) +
    geom_segment(mapping = aes(x= 1.25, xend=1.25, y=0, yend=10)) +
    geom_segment(mapping = aes(x=0, xend=1.25, y=2, yend=2)) +
    geom_segment(mapping = aes(x=0, xend=1.25, y=8, yend=8)) +
    geom_segment(mapping = aes(x=3.75, xend=5, y=2, yend=2)) +
    geom_segment(mapping = aes(x=3.75, xend=5, y=8, yend=8)) +
    geom_point(mapping = aes(x=.3, y=5), size = 10, alpha = .5) +
    geom_point(mapping = aes(x=4.7, y=5), size = 10, alpha = .5) +
    geom_segment(mapping = aes(x=.3, xend=.3, y=4.8, yend=5.2)) +
    geom_segment(mapping = aes(x=4.7, xend=4.7, y=4.8, yend=5.2)) +
    geom_point(mapping = aes(x=Ride.Clear$x, y=Ride.Clear$y, shape = Ride.Clear$Type), show.legend = T, size = 8) +
    scale_shape_manual(values=c(1,5))
}
```

```{r}
Rand.Shots = data.frame(x=c(rnorm(50, mean=2.5, sd=.5), rep(2, 5), rep(3, 5), rep(2.5, 10), rep(3.1, 10)), y=c(rnorm(50, mean=2.5, sd=.3), rep(2, 5), rep(3, 5), rep(2.7, 10), rep(3.1, 10)))
Draw.Half.Lax(Rand.Shots)

Ride.Clear = data.frame(x=(c(.25, 1.25, .25, rep(2.5, 3), rep(3.75, 3), .6, rep(1.6, 2), rep(2.85, 3), rep(4.05, 3))), y=(c(rep(c(2, 5, 8), 3), 2.2, 3.4, 7.06, 3, 5, 7, 3, 5, 7)), Type=(c(rep("Clear", 9), rep("Ride", 9))))
Draw.Full.Lax(Ride.Clear)
```


