library(shiny)
library(DT)
library(tidyverse)
library(readxl)
library(shinythemes)
FO.data <- read_excel("Data/FO.data.xlsx")
Goal.data <- read_excel("Data/Goal.data.xlsx")
Shot.data <- read_excel("Data/Shot.data.xls")